name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you are using to deploy
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install  # or any other command if you're using a different package manager

      - name: Build the project (if needed)
        run: npm run build  # or the build command that applies to your project

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # This is where GitHub Pages serves from
          folder: build  # This folder contains the built site (can be 'dist' or other depending on your setup)
